onboarding = false

[theme]
name = "catppuccin"
auto_switch = false

[keys]
prefix = "ctrl+a"

settings = "prefix+s"
workspace_picker = "prefix+w"
goto = "prefix+g"

navigate_workspace_down = "j"
navigate_workspace_up = "k"

next_workspace = "prefix+shift+n"
previous_workspace = "prefix+shift+p"

navigate_pane_left = ""
navigate_pane_down = ""
navigate_pane_up = ""
navigate_pane_right = ""

focus_pane_left = "ctrl+h"
focus_pane_down = "ctrl+j"
focus_pane_up = "ctrl+k"
focus_pane_right = "ctrl+l"

split_vertical = "prefix+v"
split_horizontal = "prefix+h"

close_pane = "prefix+x"
close_tab = "prefix+shift+x"
close_workspace = "prefix+ctrl+shift+x"

rename_pane = "prefix+r"
rename_tab = "prefix+shift+r"
rename_workspace = "prefix+ctrl+shift+r"

new_tab = "prefix+c"
next_tab = "prefix+n"
previous_tab = "prefix+p"

new_workspace = "prefix+shift+c"

detach = "prefix+d"
zoom = "prefix+enter"
copy_mode = "prefix+y"
resize_mode = "prefix+z"
reload_config = "prefix+ctrl+r"


[ui.toast]
delivery = "herdr"

[ui]
mouse_capture = true
show_agent_labels_on_pane_borders = true

[ui.sound]
enabled = true
